#!/bin/bash

file="$1"
filename="${file%.*}"
extension="${file##*.}"

#for ((i=1;i<=5;i=i+1)); do
#for ((i=15;i<=20;i=i+1)); do
#for ((i=20;i<=25;i=i+1)); do
for ((i=5;i<=35;i=i+5)); do
  ik="$i"
  if [[ "$i" -lt 10 ]]; then
    ik=0"$i"
  fi
  nfile="$filename"_"$ik"."$extension"
  convert "$file" -fuzz "$i"% -fill "#263238" -opaque "#000000" "$nfile"
done

