#!/bin/bash

bytesToHumanReadable() {
local i=${1:-0} d="" s=0 S=("B" "kB" "MB" "GB" "TB" "PB" "EB")
while ((i > 1024 && s < ${#S[@]}-1)); do
	printf -v d ".%02d" $((i % 1024 * 100 / 1024))
	i=$((i / 1024))
	s=$((s + 1))
done
echo "$i$d ${S[$s]}"
}

bytesToHumanReadable "$1"
