#!/bin/bash

current_desktop=$(xdotool get_desktop)
windows_ids=$(wmctrl -lx | tr -s ' ' | grep "tabbed.tabbed" | \
	grep "^\S* $current_desktop" | cut -d ' ' -f1)
if [ -n "$windows_ids" ]; then
	windows_eval=""
	for win_id in $windows_ids; do
		win_eval=$(xprop -id "$win_id" | grep "_NET_WM_STATE(ATOM)" | \
			grep -v _NET_WM_STATE_HIDDEN)
		if [ -n "$win_eval" ]; then
			if [ -n "$windows_eval" ]; then
				windows_eval="$windows_eval
$win_id"
				# add new line
			else
				windows_eval="$win_id"
			fi
		fi
	done
	if [ -n "$windows_eval" ]; then
		win_id=$(echo "$windows_eval" | head -n 1)
		nohup zathura "$1" -e "$win_id" >/dev/null &
		sleep 0.2
		xdotool windowraise "$win_id"
	else
		nohup tabbed -u "#263238" -t "#263238" -U "#546E7A" -T "#ABB2BF" \
		-p -1 -c zathura "$1" -e >/dev/null &
	fi
else
	nohup tabbed -u "#263238" -t "#263238" -U "#546E7A" -T "#ABB2BF" \
	-p -1 -c zathura "$1" -e >/dev/null &
fi
