#!/bin/bash

while :
do
    d_min=$(date -u +%M | sed 's/^0*//')
    d_hour=$(date -u +%H | sed 's/^0*//')
    d_day=$(date -u +%j | sed 's/^0*//')
    d_hours=$(( (d_day - 1) * 24 + d_hour + d_min / 30 + 1 ))
    p_hours=$(printf "%04d\n" "$d_hours")
	# NASA Moon Phase and Libration
	# 2021
    #moon_url="https://svs.gsfc.nasa.gov/vis/a000000/a004800/a004874/frames/730x730_1x1_30p/moon.$p_hours.jpg"
	# 2022
    #moon_url="https://svs.gsfc.nasa.gov/vis/a000000/a004900/a004955/frames/730x730_1x1_30p/moon.$p_hours.jpg"
	# 2023
    #moon_url="https://svs.gsfc.nasa.gov/vis/a000000/a005000/a005048/frames/730x730_1x1_30p/moon.$p_hours.jpg"
	# 2024
	moon_url="https://svs.gsfc.nasa.gov/vis/a000000/a005100/a005187/frames/730x730_1x1_30p/moon.$p_hours.jpg"
    moon_path="/home/ed/.moon.jpg"
    wget "$moon_url" -qO "$moon_path"
    convert "$moon_path" +sigmoidal-contrast 3.5x0 -fuzz 7% -fill "#263238" -opaque "#000000" "$moon_path"
    clear
    chafa -w 9 --color-space din99d "$moon_path"
    sleep 1800
done
