#!/bin/bash

genius_url="https://api.genius.com"
user_token="$( cat ~/.genius_token )"

media_player_metadata () {
    playing=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata 2>/dev/null)

    song=$(echo "$playing" | sed -n '/title/{n;p}' | cut -d '"' -f 2 | sed -e 's/(.*$//' -e 's/ -.*$//')
    artist=$(echo "$playing" | sed -n '/artist/{n;n;p}' | cut -d '"' -f 2)

    current_song="$artist $song"
}


search_print_lyrics () {
    columns=$(tput cols) 
    if (($columns > 40)); then
        columns=40
    fi

    clear
    printf "%*s\n" $(((${#song}+$columns)/2)) "$song"
    printf "%*s\n" $(((${#artist}+$columns)/2)) "$artist"

    current_song_str=$(echo "$current_song" | sed 's/ /%20/g')
    search_url="$genius_url/search?q=$current_song_str"
    search_html=$(curl $search_url --oauth2-bearer $user_token 2>/dev/null)

    song_id=$(echo "$search_html" | grep -o '/songs/[0-9]\+' | head -1)
    id_url="$genius_url$song_id"
    id_html=$(curl $id_url --oauth2-bearer $user_token 2>/dev/null | sed -r -e 's/</\n</g' -e 's/>/>\n/g')

    lyrics_url=$(echo "$id_html" | grep '<a href=.https://genius.com/[a-zA-Z0-9-]\+lyrics' | cut -d"'" -f2)
    lyrics_html=$(curl "$lyrics_url" 2>/dev/null | sed 's/^ \+//' | tr -d '\n'| sed -e 's/>/>\n/g' -e 's/</\n</g' | sed '/^$/d')
 
	song_lyrics=$(echo "$lyrics_html" | sed -n '/<div class="LyricsHeader/,/<div class="LyricsFooter/p' | tr -d '\n' | sed -e 's/<br>\|<br\/>/\n/g' -e 's/<a class[^>]*<\/a>//' -e 's/<h2.*<\/h2>//' -e 's/<[^>]*>//g' -e 's/\&quot;/"/g' -e "s/&#x27;/'/g" -e 's/You might also like/\n/')

    echo "$song_lyrics"

    past_song=$current_song
}


media_player_metadata
search_print_lyrics

while :
do
    media_player_metadata
    if [[ "$past_song" != "$current_song" ]]
    then
        search_print_lyrics
    fi
    sleep 0.2
done
